### ISSUE TITLE
[2023] - Pixel condition update

### ISSUE THREAD

**Issue by sroychow** [CMSTrackerDPG/Tasks#11]
This issue is opened to monitor/book-keep the updates of pixel conditions for year 2023 data taking and simulation. Pixel experts and AlcaDB contact should use this issue to report updates of conditions, add links to request of GT, validation etc in this thread as comment.

**NOTE- Do not close this issue**

**Comment by mroguljic** [comment]
GT [124X_mcRun3_2022_realistic_postEE_forPixelIneff_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/124X_mcRun3_2022_realistic_postEE_forPixelIneff_v5) has been created ([CMS-talk](https://cms-talk.web.cern.ch/t/request-creation-of-a-gt-with-preliminary-pixel-dynamic-inefficiency-settings/20385/13)). It includes the fixed dynamic inefficiency Run3 payload named SiPixelDynamicInefficiency_phase1_2023_v2_fix2. Validation datasets requested ([JIRA](https://its.cern.ch/jira/browse/PDMVRELVALS-188))

**Comment by sroychow** [comment]
New CPE tags from collision data to account for EOY annealing :- 

- Tag: SiPixelTemplateDBObject_phase1_38T_2023_v1; Rcd: SiPixelTemplateDBObjectRcd; Label: -
- Tag: SiPixel2DTemplateDBObject_phase1_38T_2023_v1; Rcd: SiPixel2DTemplateDBObjectRcd; Label: numerator
- Tag: SiPixelLorentzAngle_phase1_38T_2023_v1; Rcd: SiPixelLorentzAngleRcd; Label: -
- Tag: SiPixelGenErrorDBObject_phase1_38T_2023_v1; Rcd: SiPixelGenErrorDBObjectRcd; Label: -
Related CMS talk[ announcement](https://cms-talk.web.cern.ch/t/hlt-express-prompt-full-track-validation-of-new-2023-cpe-derived-for-bpix-l1-and-l2-annealing/23657)

**Comment by mroguljic** [comment]
New CPE tags from collision data to account for accumulated irradiation and increased HV in L1 and L2: 
- Tag: SiPixelTemplateDBObject_phase1_38T_2023_v2; Rcd: SiPixelTemplateDBObjectRcd; Label: -
-  Tag: SiPixel2DTemplateDBObject_phase1_38T_2023_v2; Rcd: SiPixel2DTemplateDBObjectRcd; Label: numerator
-  Tag: SiPixelLorentzAngle_phase1_38T_2023_v2; Rcd: SiPixelLorentzAngleRcd; Label: -
-  Tag: SiPixelGenErrorDBObject_phase1_38T_2023_v2; Rcd: SiPixelGenErrorDBObjectRcd; Label: -

CMS talk is undergoing maintenance so I am linking the related FTV: https://its.cern.ch/jira/browse/CMSALCA-221
