### ISSUE TITLE
Introducing a Tracker phase-2 geometry based on T25 but compatible with new OT/BTL boundary

### ISSUE THREAD

**Issue by emiglior** [CMSTrackerDPG/Tasks#3]
This is the first issue describing a series of changes aiming to have a more realistic description of the phase-2 Inner Tracker:
- introducing a baseline geometry with TBPX layer1 featuring 3D sensors instead of planar sensors
- new version of Pixel3DDigitizerAlgorithm with an improved description of the response of the 3D sensors before and after irradiation 

**Description**

The Tracker geometry used in the baseline CMS geometry for phase-2 is T24 [link to CMSSW_13_0_X](https://github.com/cms-sw/cmssw/blob/CMSSW_13_0_0_pre3/Configuration/Geometry/README.md).

On the other hand, T25 represents a more correct description of the actual layout of the detector chosen for phase-2, as it features 3D sensors in TBPX layer1. Unfortunately, T25 cannot be matched as it is with the latest developments of the MTD geometry (I16) as PR [39592](https://github.com/cms-sw/cmssw/pull/39592) modified the boundary between OT and MTD. Note that Tracker T31 geometry is the same as T24 geometry, but with this new boundary.

Similarly, we propose to introduce a T32 geometry which is the same as T25 but with the new OT/MTD boundary and to adopt it as the new baseline phase-2 geometry so that it can be regularly exercised with RelVals and extended physics studies so that effects related to the change in the geometry can be decoupled wrt effects due to the change in the digitizer.

This is the branch with the proposed implementation of T32: [emiglior:add_T32_cmssw_13_0_X](https://github.com/emiglior/cmssw/tree/add_T32_cmssw_13_0_X).

Note: T32 is not yet the ultimate geometry, as the actual geometry features two separate 3D sensors for each TBPX layer1 modules. The implementation of this geometry is less trivial as it requires a change of the detID scheme and will be available only later this year.

**Comment by sroychow** [comment]
PR to CMSSW - https://github.com/cms-sw/cmssw/pull/40647
Link to talk at simulation meeting - https://indico.cern.ch/event/1247289/#48-phase-2-tracker-geometry-up

Positive feedback from Geometry and Simulation groups. Will have to follow up with relval requests.
