### ISSUE TITLE
Produce Pixel Hit efficiency plots as a function of track azimuth (phi)

### ISSUE THREAD

**Issue by mmusich** [CMSTrackerDPG/Tasks#7]
Requested here: https://mattermost.web.cern.ch/cms-exp/pl/i6h4n5t9itg3u8wtyge993nbye, duly ignored by DPG.
It would greatly help in understanding phi-dependent features in the E/p harness calibrations of ECAL.

**Comment by mroguljic** [comment]
Apologies for overlooking this request. It is duly noted now and we are working on getting the results.

**Comment by mroguljic** [comment]
Plots provided in this Mattermost thread: https://mattermost.web.cern.ch/cms-exp/pl/djqnx5don3f7tbtfeoy543kuda
